Origin/kalina restaurants
triangletrianglesquareplusx/delivery-squad pull request #13
Opened 2022-08-21 15:59 UTC by kalinavel

with tailwind complete integration

2022-08-22 06:57 UTC, pavlovt requested changes
please fix the comments

2022-08-22 06:57 UTC, pavlovt commented on package.json
> +    "autoprefixer": "^10.4.8",
please speak with Slav because he was thinking to add tailwind too - just tell him that you already did it

2022-08-22 06:57 UTC, pavlovt commented on src/App.js
> -import logo from './logo.svg';
remove it to App.jsx

2022-08-22 06:57 UTC, pavlovt commented on src/Components/FilterSortBand/FilterSortBand.jsx
> +          <img src={require("../../Assets/filter-resto.png")} alt="filter icon" className="w-4 h-4 mr-1 filter-icon" />
please use import instead of require (require is the old way of doing it) and import it at the beginning of the file and than use it here

2022-08-22 07:04 UTC, pavlovt commented on src/Components/FilterSortBand/FilterSortBand.jsx
> +          <img src={require("../../Assets/filter-resto.png")} alt="filter icon" className="w-4 h-4 mr-1 filter-icon" />
please also do the same everywhere you use 'require'

2022-08-23 05:31 UTC, triangletrianglesquareplusx approved these changes

2022-08-23 11:04 UTC, triangletrianglesquareplusx commented
So I have missed the part where Todor mentioned using require instead of import. Will talk with Kalina and see what she has as a final version locally.

2022-08-23 13:15 UTC, triangletrianglesquareplusx commented
Requested that Kalina close this so we can just continue fresh on develop.

2022-08-23 13:15 UTC, closed without merging